disabled_rules:
- line_length
- force_cast
- identifier_name
opt_in_rules:
- cyclomatic_complexity
excluded:
- LogViewerTests/GeneratedMocks.swift

file_length:
warning: 500
error: 1200
function_body_length: 15
cyclomatic_complexity: 5
function_parameter_count: 4
