# Test (always)

name: Test

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory: [ QLog/QLog, QLog/QLogTests ]
    steps:
      - uses: actions/checkout@v2
      - name: Lint ${{ matrix.directory }}
        uses: norio-nomura/action-swiftlint@3.2.1
        env:
          WORKING_DIRECTORY: ${{ matrix.directory }}
    
  test:
    name: Unit Tests
    needs: lint
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.2
      - uses: maierj/fastlane-action@v2.0.1
        with:
          lane: test
